version: 2
updates:
  - package-ecosystem: "nuget"         
    directory: "/OpenDriverUpdater"    
    schedule:
      interval: "weekly"               
      day: "monday"                    
      time: "06:00"                    
    open-pull-requests-limit: 5        
